company:
  legal_name: "Lucas Antônio Magalhães Pereira"
  trade_name: "Mundo AEC"
  number_id: "039.993.541-00"
  cnpj: "039.993.541-00"
  address: "Rua C 154, Nª211, Jardim América"
  city: "Goiânia"
  state: "GO"
  postal: "74.275-140"
  support_email: "suporte@mundoaec.com"
  billing_email: "financeiro@mundoaec.com"
  dpo_email: "dpo@mundoaec.com"
  website: "https://www.mundoaec.com"
  jurisdiction: "Comarca de Goiânia - GO"
  effective_date: "2026-07-20"
  update_date: "2026-07-27"
